### ISSUE TITLE
Couleur de fond sur taux de remplissage (sur la liste des devices)

### ISSUE THREAD

**Issue by cyrilpradel** [AurelienConte/Heyfront#3]
Idée d'évolution 
Pour simplifier la lecture du niveau de remplissage sur l'écran de la liste des devices, voici ce que je propose : rajouter un couleur de fond sur la cellule en fonction du taux de remplissage **et** en fonction du type de contenant.

Codes HTML des couleurs
Vert : #28a745
Orange : #fd7e14
Rouge : #dc3545

Règles
Si c'est un contenant qui se vide (ex: présentoirs) : 
Si niveau <= 100% : mettre le fond en vert
Si niveau <75% : mettre le fond de la cellule en orange
Si niveau <25% : mettre le fond de la cellule en rouge

Si c'est un contenant qui se remplit (poubelles), la règle s'inverse : 
Si niveau <= 100% : mettre le fond en rouge
Si niveau <75% : mettre le fond de la cellule en orange
Si niveau <25% : mettre le fond de la cellule en vert

Pour faciliter la lecture, la font-color doit être 'whitesmoke'

Ci-joint un exemple (ne pas tenir compte des chiffres, c'était plus pour voir le nuancier) :)
En cas de bad measure, laisser la couleur par défaut.
![capture](https://user-images.githubusercontent.com/17073626/45713798-43ae9600-bb90-11e8-856e-1370338d5287.png)

**Comment by AurelienConte** [comment]
La feature sera ajoutée à la prochaine update ! ;)
