### ISSUE TITLE
Le payload de calibration est pris en compte dans les graphs

### ISSUE THREAD

**Issue by cyrilpradel** [AurelienConte/Heyfront#4]
Cf points du présentoir OF “U express Liberté 1” (3BD35E : https://app.heyliot.com/devices/view/5b4f31c7bfa749372a745563)
17/09/2018 23:11 - Mesure : 226 => à cette heure-ci, c'était un payload de géoloc

**Comment by AurelienConte** [comment]
Normalement corrigé à la prochaine update
