### ISSUE TITLE
Ajouter la possibilité de spécifier un identifiant externe pour un device

### ISSUE THREAD

**Issue by cyrilpradel** [AurelienConte/Heyfront#5]
Nos clients ont généralement déjà un identifiant pour suivre le cycle de vie de leur contenant.
Pour Ouest France, chaque présentoir est identifier avec un code numérique (ex : 5052, 5207...) mais pour l'agglo de St Malo et ses points d'apport volontaire c'est alphanumérique : SMTRI323, SMOM217 etc...
Il faut donc ajouter la possibilité aux admins de spécifier un identifiant externe pour chaque capteur en modifiant les informations d'un capteur. Cet identifiant est non obligatoire.
Cet identifiant doit être visible pour les utilisateurs normaux mais non modifiable.
Ce sera utile pour l'intégration des données des ventes Ouest France par exemple.

**Comment by AurelienConte** [comment]
Ajouté à la prochaine update ;)
